services:
  db:
    ports:
      - 5431:5432
    container_name: sample_crud_db
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=HtkBbx51087#
    volumes:
      - "C:/Back-Up/SampleCrudDB:/var/lib/postgresql/data"
    restart: always
  backend:
#    networks:
#      - nama_jaringan
    volumes:
      - "C:/Back-Up/App/log/SampleCrud:/src/main/resources/logs"
    build: .
    container_name: sample_crud_container
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://db:5432/postgres
      db-username: postgres
      db-password: HtkBbx51087#
      server-port: 8080
    depends_on:
      - db
    restart: always

