server:
  error:
    include-stacktrace: never
  port: ${server-port}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
    url: ${db-url}
    username: ${db-username}
    password: ${db-password}
#    url: jdbc:postgresql://localhost:5432/satu
#    username: postgres
#    password: HtkBbx51087#
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create-drop
    show-sql: false
  application:
    name: SampleProjectCrudApp
springdoc:
  enable-native-support: true
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    loggers:
      enabled: true
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  metrics:
    tags:
      application: springboot-3
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

